export const TEXTS = {
  COMMON: {
    LOADING: "Cargando",
    ERROR_UNKNOWN: "Ocurrió un error desconocido.",
    SUCCESS: "¡Éxito!",
    ERROR: "Error",
    CANCEL: "Cancelar",
    SAVE_CHANGES: "Guardar Cambios",
    NEW_ENTRY: "Nuevo Registro",
    MINUTES: "minutos",
    MINUTES_ABBR: "min",
    ACTIONS: "Acciones",
    DELETE: "Eliminar",
  },
  AUTH: {
    WELCOME_TITLE: "Bienvenido",
    WELCOME_SUBTITLE: "Accede a tu cuenta para registrar tus fugas de tiempo.",
    EMAIL_LABEL: "Correo Electrónico",
    EMAIL_PLACEHOLDER: "tu@email.com",
    PASSWORD_LABEL: "Contraseña",
    PASSWORD_PLACEHOLDER: "••••••••",
    SIGN_IN_TAB: "Iniciar Sesión",
    SIGN_UP_TAB: "Crear Cuenta",
    SIGN_IN_BUTTON: "Iniciar Sesión",
    SIGN_UP_BUTTON: "Crear Cuenta",
    LOADING: "Cargando...",
    SIGN_UP_SUCCESS: "¡Cuenta creada! Revisa tu correo para verificar tu email.",
    LOGIN_ERROR: (error: string) => `Error de inicio de sesión: ${error}`,
    SIGN_UP_ERROR: (error: string) => `Error al crear la cuenta: ${error}`,
  },
  NOTIFICATIONS: {
    LEAK_REGISTERED_SUCCESS: "¡Fuga registrada con éxito!",
    LEAK_UPDATED_SUCCESS: "Registro actualizado con éxito.",
    LEAK_DELETED_SUCCESS: "Registro eliminado con éxito.",
    SELECT_CATEGORY_ERROR: "Por favor, selecciona una categoría.",
    GET_DATA_ERROR: (error: string) => `Error al obtener datos: ${error}`,
    REGISTER_ERROR: (error: string) => `Error al registrar: ${error}`,
    UPDATE_ERROR: (error: string) => `Error al actualizar: ${error}`,
    DELETE_ERROR: (error: string) => `Error al eliminar: ${error}`,
  },
  SIDEBAR: {
    TITLE: "Fugas de Tiempo",
    NAV_DATA_ENTRY: "Registrar Fuga",
    NAV_LIST: "Listado",
    NAV_STATISTICS: "Estadísticas",
    NAV_LOGOUT: "Cerrar Sesión",
  },
  DATA_ENTRY: {
    TITLE: "Registra una Interrupción",
    SUBTITLE: "Selecciona una categoría y anota los detalles en segundos.",
    STEP_1_LABEL: "1. Selecciona la Causa de la Fuga",
    STEP_2_LABEL: "2. Fecha y Hora del Registro",
    STEP_3_LABEL: "3. Duración (minutos, opcional)",
    DURATION_PLACEHOLDER: "Ej: 15",
    STEP_4_LABEL: "4. Detalles Adicionales (Opcional)",
    DESCRIPTION_PLACEHOLDER: "Anota quién y qué, o descripción de la interrupción... (Ej: 'Jefe para tema no urgente')",
    SUBMIT_BUTTON: "Registrar Fuga de Tiempo",
    SUBMIT_BUTTON_LOADING: "Registrando...",
  },
  STATISTICS: {
    TITLE: "Análisis de Tiempo Perdido",
    SUBTITLE: "Visualiza los minutos totales perdidos por cada categoría de interrupción.",
    START_DATE_LABEL: "Fecha de Inicio",
    END_DATE_LABEL: "Fecha de Fin",
    GENERATE_BUTTON: "Generar Gráfico",
    GENERATE_BUTTON_LOADING: "Generando...",
    LOADING_DATA: "Cargando datos...",
    NO_DATA: "No hay datos para mostrar en el rango de fechas seleccionado.",
    CHART_BAR_TITLE: (label: string, value: number) => `${label}: ${value} minutos`,
  },
  LIST: {
    TITLE: "Gestionar Registros",
    SUBTITLE: "Edita o elimina tus fugas de tiempo directamente.",
    TABLE_HEADER_CATEGORY: "Categoría",
    TABLE_HEADER_DATETIME: "Fecha y Hora",
    TABLE_HEADER_DURATION: "Duración (min)",
    TABLE_HEADER_DESCRIPTION: "Descripción",
    NO_RECORDS: "No se han encontrado registros.",
    DELETE_CONFIRM: "¿Estás seguro de que quieres eliminar este registro?",
    DELETE_CONFIRM_TITLE: "Confirmar Eliminación",
  },
  EDIT_MODAL: {
    TITLE: "Editar Registro",
    CATEGORY_LABEL: "Categoría",
    DATETIME_LABEL: "Fecha y Hora",
    DURATION_LABEL: "Duración (minutos)",
    DESCRIPTION_LABEL: "Descripción",
  },
};
